title: Yuandong Xu
logo: /assets/img/profile.jpg
description: Yuandong Xu - GitHub Pages
show_downloads: false
google_analytics: 
remote_theme: gebeto/researcher
theme: jekyll-theme-researcher

footer: "Yuandong Xu - GitHub Pages"
footer_url: "https://edgarxu.github.io/"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata