title: Yuandong Xu
logo: /assets/img/profile.jpg
description: Yuandong Xu - GitHub Pages
show_downloads: false
# google_analytics: 
remote_theme: gebeto/researcher # Comments by Xu
# theme: jekyll-theme-leap-day # added by Xu

footer: "Yuandong Xu - GitHub Pages"
footer_url: "https://edgarxu.github.io/"

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata